// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	auth "github.com/gpabois/goservice/auth"

	mock "github.com/stretchr/testify/mock"

	result "github.com/gpabois/gostd/result"
)

// IAuthenticationService is an autogenerated mock type for the IAuthenticationService type
type IAuthenticationService struct {
	mock.Mock
}

type IAuthenticationService_Expecter struct {
	mock *mock.Mock
}

func (_m *IAuthenticationService) EXPECT() *IAuthenticationService_Expecter {
	return &IAuthenticationService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields: strategy
func (_m *IAuthenticationService) Authenticate(strategy auth.AuthenticationStrategy) result.Result[interface{}] {
	ret := _m.Called(strategy)

	var r0 result.Result[interface{}]
	if rf, ok := ret.Get(0).(func(auth.AuthenticationStrategy) result.Result[interface{}]); ok {
		r0 = rf(strategy)
	} else {
		r0 = ret.Get(0).(result.Result[interface{}])
	}

	return r0
}

// IAuthenticationService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type IAuthenticationService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - strategy auth.AuthenticationStrategy
func (_e *IAuthenticationService_Expecter) Authenticate(strategy interface{}) *IAuthenticationService_Authenticate_Call {
	return &IAuthenticationService_Authenticate_Call{Call: _e.mock.On("Authenticate", strategy)}
}

func (_c *IAuthenticationService_Authenticate_Call) Run(run func(strategy auth.AuthenticationStrategy)) *IAuthenticationService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(auth.AuthenticationStrategy))
	})
	return _c
}

func (_c *IAuthenticationService_Authenticate_Call) Return(_a0 result.Result[interface{}]) *IAuthenticationService_Authenticate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IAuthenticationService_Authenticate_Call) RunAndReturn(run func(auth.AuthenticationStrategy) result.Result[interface{}]) *IAuthenticationService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewIAuthenticationService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAuthenticationService creates a new instance of IAuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAuthenticationService(t mockConstructorTestingTNewIAuthenticationService) *IAuthenticationService {
	mock := &IAuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
