// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Media is an autogenerated mock type for the Media type
type Media struct {
	mock.Mock
}

type Media_Expecter struct {
	mock *mock.Mock
}

func (_m *Media) EXPECT() *Media_Expecter {
	return &Media_Expecter{mock: &_m.Mock}
}

// MimeType provides a mock function with given fields:
func (_m *Media) MimeType() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Media_MimeType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MimeType'
type Media_MimeType_Call struct {
	*mock.Call
}

// MimeType is a helper method to define mock.On call
func (_e *Media_Expecter) MimeType() *Media_MimeType_Call {
	return &Media_MimeType_Call{Call: _e.mock.On("MimeType")}
}

func (_c *Media_MimeType_Call) Run(run func()) *Media_MimeType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Media_MimeType_Call) Return(_a0 string) *Media_MimeType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Media_MimeType_Call) RunAndReturn(run func() string) *Media_MimeType_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMedia interface {
	mock.TestingT
	Cleanup(func())
}

// NewMedia creates a new instance of Media. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMedia(t mockConstructorTestingTNewMedia) *Media {
	mock := &Media{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
